---
# `semantic-release` configuration and plugins setup
# https://github.com/semantic-release/semantic-release
branches: master
tagFormat: '${version}'
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: ci
          release: patch
        - type: build
          release: patch
        - type: refactor
          release: patch

  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # `@semantic-release/npm` will publish to https://npm.pkg.github.com/
  - - '@semantic-release/npm'

  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md

  - - '@semantic-release/github'

  - - '@semantic-release/git'
    - assets:
        - package.json
        - CHANGELOG.md
      message: 'chore(release): publish ${nextRelease.version} [skip ci]'
