name: Health check

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  lint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          eslint_flags: packages/

  spelling:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: reviewdog/action-misspell@v1
        with:
          exclude: .yarn/*
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          ignore: center,color,normalize
          level: info
          locale: US
