# This workflow will create a new release using `semantic-release` on each push to `master`
# See https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md

name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: semantic release
    runs-on: ubuntu-latest
    # Skip releasing again on a release commit
    # Github Actions do not honour [skip ci] by default
    # See https://github.community/t/github-actions-does-not-respect-skip-ci/17325/9
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: run semantic release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 17.1.2
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/npm
            @semantic-release/github
            @semantic-release/changelog
            @semantic-release/git
