name: Start release
on: [workflow_dispatch]

jobs:
  start-releasee:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: merge develop -> master
        run: git merge develop

      # Pushing to `master` will trigger `release` job below
      - name: push master
        run: git push origin master
