name: Start release
on: [workflow_dispatch]

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: checkout master
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin master
          git checkout --progress --force -B master refs/remotes/origin/master

      - name: merge develop -> master
        run: git merge develop

      # Pushing to `master` will trigger `release` job below
      - name: push master
        run: git push origin master
